### PR TITLE
Fixed retrieval of wrong sibling

### PR DESCRIPTION
**Pull request by saschagrunert**

### CODE REVIEW

**Comment by SimonSapin** [comment]
Looks good, thanks!

Note however that I don’t really intend for this to be a project maintained over time, it is rather publishing the results of one-off experiments.

**Comment by saschagrunert** [comment]
Yes I know, but I think the idtree would it worth to make it a maintained crate. ☺️

**Comment by SimonSapin** [comment]
Feel free to copy the code as a starting point to do that!

**Comment by saschagrunert** [comment]
Thank you!

**Pull request merged**
